
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azyuwdbplizuauevtmik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eXV3ZGJwbGl6dWF1ZXZ0bWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDMyMDIsImV4cCI6MjA2NDk3OTIwMn0.huuJfVQ7XuvWNjIlVnezHxR0RZY2Jcgj1eYPkzy88Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
